import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :logger, level: :info

config :uptime, UptimeWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :uptime,
  supported_config_dirs: ["/etc/uptime"],
  supported_secrets_dir: "/etc/secrets"

# Do not print debug messages in production

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
